import { buscarValoresSupabase } from "../services/buscarValoresSupabase";
console.log('base_acabamento: ')

export async function loadBaseAcabamentos(franquia) {
    const dadosBaseAcabamentos = await buscarValoresSupabase("obra_branca","Franquia_id", franquia);
    // console.log('dadosBaseAcabamentos: ', dadosBaseAcabamentos)
    return {
        garagem: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 472)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 412)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 447)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 473)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 412)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 448)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 476)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 412)?.total_price) || 115.86,
            },
        },
        sala: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        cozinha: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        areaGourmet: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        areaServico: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        despensa: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,

            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                
            },
        },
        escritorio: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        quartos: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                suite: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                suite: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                suite: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        lavabos: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
        banheiros: {
            standard: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            premium: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
            supreme: {
                piso: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                pintura: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                forro: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                peitoril: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                porta: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                esquadria: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                loucas: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
                marmore: Number(dadosBaseAcabamentos.find(item => item.workItemId_scienge === 445)?.total_price) || 115.86,
            },
        },
    }
}